## Today's Topics:

### ZIP Function in Python:

In [2]:
lst1 = [1,3,5,7,9]
lst2 = [2,4,6,8,10] # creating list 

In [3]:
lst3 = []

for n in zip(lst1,lst2): # adding elements of list index wise using for in loop and zip function
    lst3.append(sum(n))
print(lst3)

[3, 7, 11, 15, 19]


In [11]:
list((zip(lst1, lst2))) # printing both list as a zip in form of tuple combining elements of both lists sequentlly

[(1, 2), (3, 4), (5, 6), (7, 8), (9, 10)]

### Vectorized Operations in Array:

In [13]:
import numpy as np # importing numpy library

In [14]:
arr1 = np.array(lst1)
arr2 = np.array(lst2) # creating arrays using list above

In [16]:
print(arr1)
print(arr2) # printing both arrays

[1 3 5 7 9]
[ 2  4  6  8 10]


In [17]:
arr1 + arr2 # addition of both arrays sequently index wise, array always do mirror operations

array([ 3,  7, 11, 15, 19])

In [18]:
arr1 * 10 # Multiplying each element of array by 10 because vector expand in every dimension

array([10, 30, 50, 70, 90])

### Arithematic Operations on array:
Array always perform mirror operations.
* addition
* subtraction
* multiplication >>>> (Linear Algebra) and (Mirror)

In [19]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
b = np.random.randn(4,3) * 10
b

array([[  3.34759142,   2.9989627 ,   5.5890092 ],
       [  6.35978149, -11.17493946,  -6.58850168],
       [  1.19648716,  -0.92016397,  12.63652216],
       [ -2.24248619,  -3.96390099, -17.6776624 ]])

In [21]:
print(a + b) # we cannot perform mirror operations on arrays with different shapes as (3,4) and (4,3)
print(a - b) # only algebric operations are possible in arrays with different shapes   
print(a * b) # for algebric operations no. of columns of first array must be equal to no. of rows of second array

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [22]:
a @ b # We use @ sign to multiply in algebric multiplication 

array([[  10.68667112,  -37.96701209,  -40.38907729],
       [  45.33216665,  -90.20717897,  -64.55160817],
       [  79.97766217, -142.44734585,  -88.71413904]])

In [23]:
np.dot(a,b) # using dot product function in np for algebric multiplication

array([[  10.68667112,  -37.96701209,  -40.38907729],
       [  45.33216665,  -90.20717897,  -64.55160817],
       [  79.97766217, -142.44734585,  -88.71413904]])

In [24]:
a.dot(b) # using dot function of array for algebric multiplication

array([[  10.68667112,  -37.96701209,  -40.38907729],
       [  45.33216665,  -90.20717897,  -64.55160817],
       [  79.97766217, -142.44734585,  -88.71413904]])

### Functions in array:

#### Array Creation Functions:
| **Function**                         | **Description**                                              |
| ------------------------------------ | ------------------------------------------------------------ |
| `np.array(object)`                   | Creates an array from a list, tuple, or iterable             |
| `np.zeros(shape)`                    | Array filled with 0s                                         |
| `np.ones(shape)`                     | Array filled with 1s                                         |
| `np.full(shape, value)`              | Array filled with a specific value                           |
| `np.eye(N)`                          | Identity matrix of size `N × N` with 1s on the diagonal      |
| `np.identity(n)`                     | Identity matrix of size `n × n` (always square)              |
| `np.arange(start, stop, step)`       | Array with evenly spaced values                              |
| `np.linspace(start, stop, num)`      | Array with `num` evenly spaced values between start and stop |
| `np.random.rand(shape)`              | Array of random values from 0 to 1                           |
| `np.random.randint(low, high, size)` | Array of random integers in a specified range                |
| `np.zeros_like(a)`                   | Array of 0s with same shape and type as array `a`            |
| `np.ones_like(a)`                    | Array of 1s with same shape and type as array `a`            |
| `np.full_like(a, fill_value)`        | Array filled with `fill_value`, same shape and type as `a`   |
| `np.empty_like(a)`                   | Empty (uninitialized) array with same shape and type as `a`  |

#### Array Inspection & Attributes:
| Attribute/Function | Description                    |
| ------------------ | ------------------------------ |
| `arr.shape`        | Shape of array (rows, cols)    |
| `arr.ndim`         | Number of dimensions           |
| `arr.size`         | Total number of elements       |
| `arr.dtype`        | Data type of elements          |
| `arr.itemsize`     | Size (in bytes) of one element |
| `arr.T`            | Transpose of the array         |


#### Reshaping and Modifying Arrays:
| Function                       | Description                                                                |
| ------------------------------ | -------------------------------------------------------------------------- |
| `arr.reshape(shape)`           | Reshape without changing data                                              |
| `arr.flatten()`                | Flattens into 1D                                                           |
| `np.concatenate([a, b], axis)` | Combines arrays                                                            |
| `np.split(arr, sections)`      | Splits an array                                                            |
| `arr.ravel()`                  | Returns flattened array (like `flatten`, but returns a view when possible) |


#### Conversion & Type Utilities:
| **Function**                                               | **Description**                                                      |
| ---------------------------------------------------------- | -------------------------------------------------------------------- |
| `np.asarray(a, dtype=None, order=None)`                    | Converts input `a` to a NumPy array, avoiding copy if possible.      |
| `np.asanyarray(a, dtype=None)`                             | Similar to `asarray` but passes through subclasses (e.g., matrices)  |
| `np.asfarray(a, dtype=float)`                              | Converts input to an ndarray of floats                               |
| `np.require(a, dtype=None, requirements=None)`             | Ensures array meets specified requirements (e.g., writable, aligned) |
| `np.astype(dtype, order='K', casting='unsafe', copy=True)` | Method on arrays to convert to different dtype                       |
| `np.copy(a, order='K')`                                    | Creates a copy of array `a`                                          |
| `np.squeeze(a, axis=None)`                                 | Removes single-dimensional entries from the shape of an array        |
| `np.expand_dims(a, axis)`                                  | Expands array shape by inserting a new axis                          |


#### Mathematical Functions:
| Function                       | Description              |
| ------------------------------ | ------------------------ |
| `np.sum(arr)`                  | Sum of all elements      |
| `np.mean(arr)`                 | Mean of array            |
| `np.std(arr)`                  | Standard deviation       |
| `np.var(arr)`                  | Variance                 |
| `np.min(arr)` / `np.max(arr)`  | Minimum / Maximum        |
| `np.argmin()` / `np.argmax()`  | Index of min/max         |
| `np.cumsum()` / `np.cumprod()` | Cumulative sum / product |


#### Logical and Comparison Operations:
| Function                      | Description                    |
| ----------------------------- | ------------------------------ |
| `arr > value`                 | Element-wise comparison        |
| `np.where(condition, x, y)`   | Conditional selection          |
| `np.all(arr)` / `np.any(arr)` | Checks all / any True          |
| `np.isin(arr, [values])`      | Checks if elements are in list |
| `np.logical_and(x, y)`        | Logical AND                    |
| `np.logical_or(x, y)`         | Logical OR                     |


#### Sorting & Searching:
| Function                      | Description                            |
| ----------------------------- | -------------------------------------- |
| `np.sort(arr)`                | Returns sorted array                   |
| `arr.sort()`                  | Sorts in-place                         |
| `np.argsort(arr)`             | Returns indices that would sort array  |
| `np.unique(arr)`              | Unique elements                        |
| `np.searchsorted(arr, value)` | Index where element should be inserted |


#### Broadcasting & Vectorized Operations:
NumPy lets you apply operations to arrays without explicit loops:

In [25]:
arr = np.array([1, 2, 3])
arr + 10  # [11 12 13]
arr * 2   # [2 4 6]

array([2, 4, 6])

#### Copying vs. Views:
| Function     | Description                   |
| ------------ | ----------------------------- |
| `arr.copy()` | Returns a deep copy           |
| `arr.view()` | Returns a shallow copy (view) |


#### Matrix Operations:
| Function           | Description                         |
| ------------------ | ----------------------------------- |
| `np.dot(a, b)`     | Dot product                         |
| `np.matmul(a, b)`  | Matrix multiplication               |
| `a @ b`            | Shorthand for matrix multiplication |
| `np.linalg.inv(a)` | Matrix inverse                      |
| `np.linalg.det(a)` | Determinant                         |
| `np.linalg.eig(a)` | Eigenvalues and eigenvectors        |


#### Summary Table:
| Category                        | Examples                                                                       |
| ------------------------------- | ------------------------------------------------------------------------------ |
| **Creation**                    | `np.array`, `np.zeros`, `np.ones`, `np.arange`, `np.random.rand`               |
| **Attributes**                  | `shape`, `ndim`, `dtype`, `T`                                                  |
| **Math**                        | `sum`, `mean`, `std`, `min`, `max`, `cumsum`                                   |
| **Reshape/Modify**              | `reshape`, `flatten`, `concatenate`, `split`                                   |
| **Logic**                       | `where`, `all`, `any`, `isin`, `logical_and`                                   |
| **Sort/Search**                 | `sort`, `argsort`, `unique`, `searchsorted`                                    |
| **Linear Algebra**              | `dot`, `matmul`, `inv`, `eig`                                                  |
| **Conversion & Type Utilities** | `asarray`, `asanyarray`, `astype`, `copy`, `require`, `squeeze`, `expand_dims` |


### Bolean Indexing in Arrays:

In [26]:
arr3 = np.arange(101,151).reshape(5,10) # creating a 2 dimensional array
arr3

array([[101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150]])

In [27]:
arr3 > 130 # applying bolean indexing on array

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [28]:
arr4 = np.random.random_integers(1,30, (5,6)) # creating 2 dimensional array using random integer function and shape
arr4

C:\Users\Hp\AppData\Local\Temp\ipykernel_5636\1581105877.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 30 + 1) instead
  arr4 = np.random.random_integers(1,30, (5,6))


array([[13,  2, 14, 11, 27,  3],
       [ 9,  1, 19,  3,  8, 27],
       [27, 10,  8, 15, 20, 20],
       [ 7, 22, 12, 23, 13,  8],
       [23, 20, 10, 26, 23,  9]], dtype=int32)

In [40]:
arr4 > 20 # applying bolean indexing on array

array([[False, False, False, False,  True, False],
       [False, False, False, False, False,  True],
       [ True, False, False, False, False, False],
       [False,  True, False,  True, False, False],
       [ True, False, False,  True,  True, False]])

In [31]:
print(arr4[arr4 > 20]) # sorting required values using bolean operaions 

[27 27 27 22 23 23 26 23]


In [32]:
arr5 = np.random.random_integers(1,21, 20) # creating 1 dimesional array
arr5 

C:\Users\Hp\AppData\Local\Temp\ipykernel_5636\1809472352.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 21 + 1) instead
  arr5 = np.random.random_integers(1,21, 20)


array([ 6, 20,  5, 21, 19, 18,  9,  9,  8,  7,  4, 21,  7, 17,  3, 10, 10,
        1, 17, 11], dtype=int32)

In [34]:
arr5[arr5 >= 10] # print values greaterthan and equal to 10

array([20, 21, 19, 18, 21, 17, 10, 10, 17, 11], dtype=int32)

In [35]:
arr5[~(arr5 >= 10)] # print values lessthan and equal to 10, use ~ sign to invert the condition

array([6, 5, 9, 9, 8, 7, 4, 7, 3, 1], dtype=int32)

In [36]:
arr5[arr5 % 2 == 0] # print even numbers 

array([ 6, 20, 18,  8,  4, 10, 10], dtype=int32)

In [37]:
arr5[~(arr5 % 2 == 0)] # print odd numbers, use ~ sign to invert the condition

array([ 5, 21, 19,  9,  9,  7, 21,  7, 17,  3,  1, 17, 11], dtype=int32)

In [39]:
arr5[(arr5 > 5) & (arr5 < 10)] # print values greaterthan 5 and lessthan 10

array([6, 9, 9, 8, 7, 7], dtype=int32)

### Fancy Indexing:

In [41]:
arr4 = np.random.random_integers(1,30, (5,6)) # creating 2 dimensional array
arr4

C:\Users\Hp\AppData\Local\Temp\ipykernel_5636\1581105877.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 30 + 1) instead
  arr4 = np.random.random_integers(1,30, (5,6))


array([[ 6,  8, 11,  6, 19, 18],
       [23, 18, 10, 14,  7, 19],
       [24,  8, 27, 30,  3, 14],
       [16, 22, 30,  9, 23, 22],
       [ 8,  1, 13, 18, 13,  3]], dtype=int32)

In [43]:
arr4[[2,1,3,1]] # print selected rows of the array

array([[24,  8, 27, 30,  3, 14],
       [23, 18, 10, 14,  7, 19],
       [16, 22, 30,  9, 23, 22],
       [23, 18, 10, 14,  7, 19]], dtype=int32)

In [44]:
arr4[[2,1,0], [5,2,0]] # print selected values of the array, values will be selected in the form of order pairs e.g (R,C) = (2,5)(1,2)(0,0)

array([14, 10,  6], dtype=int32)

In [45]:
from numpy.linalg import inv, qr # imports 2 specific linear algebra functions from module numpy.linalg